# Generated by Django 3.1.3 on 2020-11-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='client',
            new_name='company',
        ),
    ]
