# Generated by Django 3.1.3 on 2020-11-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201109_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='_active_project',
            field=models.PositiveIntegerField(default=None, editable=False, null=True),
        ),
    ]
