# Generated by Django 3.1.3 on 2020-11-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20201111_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='_active_project',
            field=models.PositiveIntegerField(default=None, editable=False, null=True),
        ),
    ]
