# Generated by Django 3.1.3 on 2020-11-08 14:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('rating_reason', models.CharField(max_length=255)),
                ('employee_feedback', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SurveillanceOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.project')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ManyToManyField(through='performance_register.EvaluationAnswer', to='performance_register.EvaluationQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualMonthlyRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_entries', models.PositiveIntegerField()),
                ('total_shifts', models.PositiveIntegerField()),
                ('day_shifts', models.PositiveIntegerField()),
                ('incidents', models.PositiveIntegerField()),
                ('non_compliances', models.PositiveIntegerField()),
                ('observations', models.PositiveIntegerField()),
                ('covid19_non_compliances', models.PositiveIntegerField(default=0)),
                ('mistakes', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('surveillance_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance_register.surveillanceofficer')),
            ],
        ),
        migrations.AddField(
            model_name='evaluationanswer',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance_register.supervisorevaluation'),
        ),
        migrations.AddField(
            model_name='evaluationanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance_register.evaluationquestion'),
        ),
    ]
