# Generated by Django 3.1.3 on 2020-11-08 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('performance_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveillanceofficer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.project'),
        ),
    ]
