# Generated by Django 3.1.3 on 2020-11-08 14:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance_register', '0002_auto_20201108_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorevaluation',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='supervisorevaluation',
            name='surveillance_officer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='performance_register.surveillanceofficer'),
            preserve_default=False,
        ),
    ]
