# Generated by Django 3.1.3 on 2020-11-08 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance_register', '0006_individualmonthlyrating_supervisor_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualmonthlyrating',
            name='supervisor_evaluation',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance_register.supervisorevaluation'),
        ),
    ]
