# Generated by Django 3.1.3 on 2020-11-09 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201109_1440'),
        ('performance_register', '0007_auto_20201108_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationanswer',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_answer', to='performance_register.supervisorevaluation'),
        ),
        migrations.AlterField(
            model_name='individualmonthlyrating',
            name='supervisor_evaluation',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_monthly_rating', to='performance_register.supervisorevaluation'),
        ),
        migrations.AlterField(
            model_name='individualmonthlyrating',
            name='surveillance_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_monthly_rating', to='performance_register.surveillanceofficer'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='dashboard.project'),
        ),
        migrations.AlterField(
            model_name='supervisorevaluation',
            name='surveillance_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_evaluation', to='performance_register.surveillanceofficer'),
        ),
        migrations.AlterField(
            model_name='surveillanceofficer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveillance_officer', to='dashboard.project'),
        ),
    ]
