# Generated by Django 3.1.3 on 2020-11-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_register', '0008_auto_20201109_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualmonthlyrating',
            name='day_shifts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
