# Generated by Django 3.1.3 on 2020-11-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_register', '0009_auto_20201111_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorevaluation',
            name='questions',
            field=models.ManyToManyField(related_name='evaluation_question', through='performance_register.EvaluationAnswer', to='performance_register.EvaluationQuestion'),
        ),
    ]
